# =========================================
# SeatSense Supabase Project Configuration
# =========================================
project_id = "seatsense"

[functions]
  [functions.estimate-occupancy]
    verify_jwt = false
    import_map = "import_map.json"

  [functions.get-noise-level]
    verify_jwt = false
    import_map = "import_map.json"

  [functions.get-distance]
    verify_jwt = false
    import_map = "import_map.json"
